version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "VeryStr0ngP@ssw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_server:/var/opt/mssql
    restart: always
    platform: linux/amd64
    hostname: sql

  backend:
    build:
      context: ./FirstProject/FirstProject.Presentation
      dockerfile: Dockerfile
    container_name: firstproject_api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sql,1433;Database=FirstProjectDatabase;User Id=sa;Password=VeryStr0ngP@ssw0rd;TrustServerCertificate=True;"
    ports:
      - "5120:8080"
    depends_on:
      - sqlserver
    restart: always
    platform: linux/amd64
    networks:
      - appnet

volumes:
  sql_server:

networks:
  appnet:
